export enum SERVICES {
  DAHUA_EVENT_SERVICE = 'DAHUA_EVENT_SERVICE',
  MQTT_SERVICE = 'MQTT_SERVICE',
}

export enum REPOSITORY {
  DAHUA_EVENT_REPOSITORY = 'DAHUA_EVENT_REPOSITORY',
}

export enum ADAPTERS {
  DAHUA_EVENT_ADAPTER = 'DAHUA_EVENT_ADAPTER',
  MQTT_ADAPTER = 'MQTT_ADAPTER',
}

export enum DOMAIN {
  HEALTH = 'health',
  DAHUA_EVENT = 'dahua_event',
}
